package com.example.finalPro.command;

public enum CommandType {
    LOGIN,
    VIEW_FACULTIES,
    VIEW_FACULTY,
    LOGOUT,
    REGISTRATION,
    APPLY,
    PERSONAL_SETTINGS,
    VIEW_APPLICANTS,
    OPEN_ENROLLMENT,
    CLOSE_ENROLLMENT,
    VIEW_ENROLLMENTS,
    EDIT_PROFILE,
    CANCEL_APPLICATION,
    VIEW_APPLICATION,
    VIEW_SUBJECTS,
    ADD_SUBJECT,
    DELETE_SUBJECT,
    ADD_FACULTY,
    DELETE_FACULTY;
}
